apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: team-a
spec:
  # We don't use type LoadBalancer intentionally
  # because it creates a NodePort and the platform
  # team maintains a production Ingress for us
  type: ClusterIP
  selector:
    app: podinfo
  ports:
    - name: http
      port: 9898
      protocol: TCP
      targetPort: http
    - port: 9999
      targetPort: grpc
      protocol: TCP
      name: grpc
